# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Wed Dec 11 17:24:38 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 371)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 681, 355))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab0 = QtWidgets.QWidget()
        self.tab0.setObjectName("tab0")
        self.widget = QtWidgets.QWidget(self.tab0)
        self.widget.setGeometry(QtCore.QRect(6, 10, 661, 311))
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(2)
        self.gridLayout_5.setVerticalSpacing(4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_ping_vts_server = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ping_vts_server.sizePolicy().hasHeightForWidth())
        self.button_ping_vts_server.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.button_ping_vts_server.setFont(font)
        self.button_ping_vts_server.setObjectName("button_ping_vts_server")
        self.horizontalLayout.addWidget(self.button_ping_vts_server)
        self.button_start_vts_server = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.button_start_vts_server.setFont(font)
        self.button_start_vts_server.setCheckable(True)
        self.button_start_vts_server.setObjectName("button_start_vts_server")
        self.horizontalLayout.addWidget(self.button_start_vts_server)
        self.gridLayout_5.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.lineEdit_test_output_location = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.lineEdit_test_output_location.setFont(font)
        self.lineEdit_test_output_location.setObjectName("lineEdit_test_output_location")
        self.horizontalLayout_11.addWidget(self.lineEdit_test_output_location)
        spacerItem1 = QtWidgets.QSpacerItem(84, 19, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 6, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_11 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.lineEdit_vts_config_file = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit_vts_config_file.setFont(font)
        self.lineEdit_vts_config_file.setObjectName("lineEdit_vts_config_file")
        self.horizontalLayout_13.addWidget(self.lineEdit_vts_config_file)
        self.button_load_vts_config = QtWidgets.QPushButton(self.widget)
        self.button_load_vts_config.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.button_load_vts_config.setFont(font)
        self.button_load_vts_config.setObjectName("button_load_vts_config")
        self.horizontalLayout_13.addWidget(self.button_load_vts_config)
        self.gridLayout_5.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_10.addWidget(self.label_14)
        self.lineEdit_test_dir = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.lineEdit_test_dir.setFont(font)
        self.lineEdit_test_dir.setObjectName("lineEdit_test_dir")
        self.horizontalLayout_10.addWidget(self.lineEdit_test_dir)
        self.button_tests_load = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_tests_load.setFont(font)
        self.button_tests_load.setObjectName("button_tests_load")
        self.horizontalLayout_10.addWidget(self.button_tests_load)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 5, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.listWidget_loaded_tests = QtWidgets.QListWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.listWidget_loaded_tests.setFont(font)
        self.listWidget_loaded_tests.setDragEnabled(True)
        self.listWidget_loaded_tests.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_loaded_tests.setAlternatingRowColors(True)
        self.listWidget_loaded_tests.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_loaded_tests.setMovement(QtWidgets.QListView.Snap)
        self.listWidget_loaded_tests.setObjectName("listWidget_loaded_tests")
        self.horizontalLayout_12.addWidget(self.listWidget_loaded_tests)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_tests_start = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_tests_start.sizePolicy().hasHeightForWidth())
        self.button_tests_start.setSizePolicy(sizePolicy)
        self.button_tests_start.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_tests_start.setFont(font)
        self.button_tests_start.setObjectName("button_tests_start")
        self.verticalLayout_2.addWidget(self.button_tests_start)
        self.button_tests_stop = QtWidgets.QPushButton(self.widget)
        self.button_tests_stop.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_tests_stop.sizePolicy().hasHeightForWidth())
        self.button_tests_stop.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_tests_stop.setFont(font)
        self.button_tests_stop.setObjectName("button_tests_stop")
        self.verticalLayout_2.addWidget(self.button_tests_stop)
        self.horizontalLayout_12.addLayout(self.verticalLayout_2)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_21 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_2.addWidget(self.label_21)
        spacerItem2 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_22 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.lineEdit_manual_vmm_sn_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_manual_vmm_sn_2.setMaxLength(5)
        self.lineEdit_manual_vmm_sn_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_manual_vmm_sn_2.setObjectName("lineEdit_manual_vmm_sn_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_manual_vmm_sn_2)
        self.button_ping_fpga = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ping_fpga.sizePolicy().hasHeightForWidth())
        self.button_ping_fpga.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_ping_fpga.setFont(font)
        self.button_ping_fpga.setObjectName("button_ping_fpga")
        self.horizontalLayout_2.addWidget(self.button_ping_fpga)
        self.button_power_fpga = QtWidgets.QPushButton(self.widget)
        self.button_power_fpga.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_power_fpga.setFont(font)
        self.button_power_fpga.setCheckable(True)
        self.button_power_fpga.setObjectName("button_power_fpga")
        self.horizontalLayout_2.addWidget(self.button_power_fpga)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_23 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_3.addWidget(self.label_23)
        spacerItem3 = QtWidgets.QSpacerItem(34, 14, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.button_ping_vmm = QtWidgets.QPushButton(self.widget)
        self.button_ping_vmm.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ping_vmm.sizePolicy().hasHeightForWidth())
        self.button_ping_vmm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_ping_vmm.setFont(font)
        self.button_ping_vmm.setObjectName("button_ping_vmm")
        self.horizontalLayout_3.addWidget(self.button_ping_vmm)
        self.button_power_vmm = QtWidgets.QPushButton(self.widget)
        self.button_power_vmm.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_power_vmm.setFont(font)
        self.button_power_vmm.setCheckable(True)
        self.button_power_vmm.setObjectName("button_power_vmm")
        self.horizontalLayout_3.addWidget(self.button_power_vmm)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_18 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.button_do_manual_vmm_sn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_do_manual_vmm_sn.setFont(font)
        self.button_do_manual_vmm_sn.setCheckable(True)
        self.button_do_manual_vmm_sn.setObjectName("button_do_manual_vmm_sn")
        self.horizontalLayout_9.addWidget(self.button_do_manual_vmm_sn)
        self.lineEdit_manual_vmm_sn = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_manual_vmm_sn.setMaxLength(5)
        self.lineEdit_manual_vmm_sn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_manual_vmm_sn.setObjectName("lineEdit_manual_vmm_sn")
        self.horizontalLayout_9.addWidget(self.lineEdit_manual_vmm_sn)
        self.button_ping_camera = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ping_camera.sizePolicy().hasHeightForWidth())
        self.button_ping_camera.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_ping_camera.setFont(font)
        self.button_ping_camera.setObjectName("button_ping_camera")
        self.horizontalLayout_9.addWidget(self.button_ping_camera)
        self.button_acquire_vmm_serial = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_acquire_vmm_serial.setFont(font)
        self.button_acquire_vmm_serial.setObjectName("button_acquire_vmm_serial")
        self.horizontalLayout_9.addWidget(self.button_acquire_vmm_serial)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 4, 0, 1, 1)
        self.gridLayout_5.setRowStretch(0, 2)
        self.tabWidget.addTab(self.tab0, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.widget1 = QtWidgets.QWidget(self.tab1)
        self.widget1.setGeometry(QtCore.QRect(0, 10, 671, 241))
        self.widget1.setObjectName("widget1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_8.setSpacing(4)
        self.gridLayout_8.setContentsMargins(4, -1, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_12.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_12.setVerticalSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_6.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_15.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_4.addWidget(self.pushButton_15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_fpga_configure = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_fpga_configure.setFont(font)
        self.button_fpga_configure.setObjectName("button_fpga_configure")
        self.horizontalLayout_5.addWidget(self.button_fpga_configure)
        self.button_ping_fpga2 = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_ping_fpga2.setFont(font)
        self.button_ping_fpga2.setObjectName("button_ping_fpga2")
        self.horizontalLayout_5.addWidget(self.button_ping_fpga2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.frame_5 = QtWidgets.QFrame(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(1)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout_12.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_13.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_13.setVerticalSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_12.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_16.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_6.addWidget(self.pushButton_16)
        self.gridLayout_13.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_vmm_configure = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_vmm_configure.setFont(font)
        self.button_vmm_configure.setObjectName("button_vmm_configure")
        self.horizontalLayout_7.addWidget(self.button_vmm_configure)
        self.button_vmm_reset = QtWidgets.QPushButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_vmm_reset.setFont(font)
        self.button_vmm_reset.setObjectName("button_vmm_reset")
        self.horizontalLayout_7.addWidget(self.button_vmm_reset)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(1)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_11.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_6)
        self.gridLayout_13.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.button_acq_on = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_acq_on.setFont(font)
        self.button_acq_on.setObjectName("button_acq_on")
        self.horizontalLayout_8.addWidget(self.button_acq_on)
        self.button_acq_off = QtWidgets.QPushButton(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.button_acq_off.setFont(font)
        self.button_acq_off.setObjectName("button_acq_off")
        self.horizontalLayout_8.addWidget(self.button_acq_off)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.gridLayout_10.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(690, 470, 162, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("interface/resources/uci.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("interface/resources/ntua.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("interface/resources/brookhaven.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(700, 34, 162, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("interface/resources/vts_logo.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.centralwidget)
        self.frame_8.setGeometry(QtCore.QRect(700, 142, 162, 221))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(2)
        self.frame_8.setObjectName("frame_8")
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setGeometry(QtCore.QRect(5, 5, 151, 21))
        self.frame_7.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_vts_server_status = QtWidgets.QLabel(self.frame_7)
        self.label_vts_server_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vts_server_status.setObjectName("label_vts_server_status")
        self.gridLayout_2.addWidget(self.label_vts_server_status, 0, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setGeometry(QtCore.QRect(5, 80, 152, 21))
        self.frame_10.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setObjectName("frame_10")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setGeometry(QtCore.QRect(5, 30, 151, 21))
        self.frame_11.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_vts_vmm_sn = QtWidgets.QLabel(self.frame_11)
        self.label_vts_vmm_sn.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vts_vmm_sn.setObjectName("label_vts_vmm_sn")
        self.gridLayout_3.addWidget(self.label_vts_vmm_sn, 0, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setGeometry(QtCore.QRect(5, 55, 151, 21))
        self.frame_12.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_current_test = QtWidgets.QLabel(self.frame_12)
        self.label_current_test.setAlignment(QtCore.Qt.AlignCenter)
        self.label_current_test.setObjectName("label_current_test")
        self.gridLayout_15.addWidget(self.label_current_test, 0, 0, 1, 1)
        self.progressBar_current_test_progress = QtWidgets.QProgressBar(self.frame_8)
        self.progressBar_current_test_progress.setGeometry(QtCore.QRect(5, 148, 152, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_current_test_progress.sizePolicy().hasHeightForWidth())
        self.progressBar_current_test_progress.setSizePolicy(sizePolicy)
        self.progressBar_current_test_progress.setSizeIncrement(QtCore.QSize(0, 0))
        self.progressBar_current_test_progress.setBaseSize(QtCore.QSize(0, 4))
        self.progressBar_current_test_progress.setProperty("value", 24)
        self.progressBar_current_test_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_current_test_progress.setInvertedAppearance(False)
        self.progressBar_current_test_progress.setObjectName("progressBar_current_test_progress")
        self.frame_13 = QtWidgets.QFrame(self.frame_8)
        self.frame_13.setGeometry(QtCore.QRect(5, 174, 152, 41))
        self.frame_13.setStyleSheet("")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_13.setLineWidth(2)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setStyleSheet("background-color: rgb(244, 255, 122)")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setLineWidth(0)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_test_status = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_test_status.setFont(font)
        self.label_test_status.setStyleSheet("colo")
        self.label_test_status.setText("")
        self.label_test_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_test_status.setObjectName("label_test_status")
        self.gridLayout_6.addWidget(self.label_test_status, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_14, 0, 0, 1, 1)
        self.label_test_count = QtWidgets.QLabel(self.frame_8)
        self.label_test_count.setGeometry(QtCore.QRect(60, 129, 42, 16))
        self.label_test_count.setAlignment(QtCore.Qt.AlignCenter)
        self.label_test_count.setObjectName("label_test_count")
        self.frame_15 = QtWidgets.QFrame(self.frame_8)
        self.frame_15.setGeometry(QtCore.QRect(5, 105, 152, 21))
        self.frame_15.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_15.setObjectName("frame_15")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 22))
        self.menubar.setObjectName("menubar")
        self.menuVMM_Testing_Software = QtWidgets.QMenu(self.menubar)
        self.menuVMM_Testing_Software.setObjectName("menuVMM_Testing_Software")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuVMM_Testing_Software.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "VMM Testing Software", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "VTS Server", None, -1))
        self.button_ping_vts_server.setText(QtWidgets.QApplication.translate("MainWindow", "Alive?", None, -1))
        self.button_start_vts_server.setText(QtWidgets.QApplication.translate("MainWindow", "   Start   ", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Out. Dir  ", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "VTS Config  ", None, -1))
        self.button_load_vts_config.setText(QtWidgets.QApplication.translate("MainWindow", "   Load   ", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Test Dir  ", None, -1))
        self.button_tests_load.setText(QtWidgets.QApplication.translate("MainWindow", "Load Tests", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Tests      ", None, -1))
        self.button_tests_start.setText(QtWidgets.QApplication.translate("MainWindow", "START", None, -1))
        self.button_tests_stop.setText(QtWidgets.QApplication.translate("MainWindow", "STOP", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "FPGA ", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "IP ", None, -1))
        self.button_ping_fpga.setText(QtWidgets.QApplication.translate("MainWindow", "Alive?", None, -1))
        self.button_power_fpga.setText(QtWidgets.QApplication.translate("MainWindow", "      ON       ", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "VMM  ", None, -1))
        self.button_ping_vmm.setText(QtWidgets.QApplication.translate("MainWindow", "Alive?", None, -1))
        self.button_power_vmm.setText(QtWidgets.QApplication.translate("MainWindow", "      ON       ", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Camera  ", None, -1))
        self.button_do_manual_vmm_sn.setText(QtWidgets.QApplication.translate("MainWindow", "Manual VMM SN", None, -1))
        self.button_ping_camera.setText(QtWidgets.QApplication.translate("MainWindow", "Alive?", None, -1))
        self.button_acquire_vmm_serial.setText(QtWidgets.QApplication.translate("MainWindow", "   Get SN   ", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab0), QtWidgets.QApplication.translate("MainWindow", "VTS Control", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "FPGA", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Config   ", None, -1))
        self.pushButton_6.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.pushButton_15.setText(QtWidgets.QApplication.translate("MainWindow", "Show", None, -1))
        self.button_fpga_configure.setText(QtWidgets.QApplication.translate("MainWindow", "Configure", None, -1))
        self.button_ping_fpga2.setText(QtWidgets.QApplication.translate("MainWindow", "FPGA Alive?", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "none", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "VMM", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Config   ", None, -1))
        self.pushButton_12.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.pushButton_16.setText(QtWidgets.QApplication.translate("MainWindow", "Show", None, -1))
        self.button_vmm_configure.setText(QtWidgets.QApplication.translate("MainWindow", "Configure", None, -1))
        self.button_vmm_reset.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "none", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "DAQ", None, -1))
        self.button_acq_on.setText(QtWidgets.QApplication.translate("MainWindow", "ACQ on", None, -1))
        self.button_acq_off.setText(QtWidgets.QApplication.translate("MainWindow", "ACQ off", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), QtWidgets.QApplication.translate("MainWindow", "Frontend Control", None, -1))
        self.label_vts_server_status.setText(QtWidgets.QApplication.translate("MainWindow", "none", None, -1))
        self.label_vts_vmm_sn.setText(QtWidgets.QApplication.translate("MainWindow", "none", None, -1))
        self.label_current_test.setText(QtWidgets.QApplication.translate("MainWindow", "none", None, -1))
        self.label_test_count.setText(QtWidgets.QApplication.translate("MainWindow", "N/M", None, -1))
        self.menuVMM_Testing_Software.setTitle(QtWidgets.QApplication.translate("MainWindow", "VMM Testing Software", None, -1))

